// Creative field / service taxonomy for the public supplier intake form.
// Ported verbatim from the original riyadh-winter-2026.netlify.app
// /supplier-intake.html page (Basa Studio's pre-Lamha "join our network"
// form) so the same 16 fields and ~170 services keep meaning the same
// thing downstream — the submission payload this page posts is read by
// the same review process that read the old form's submissions.

export const CREATIVE_FIELDS = [
  "Music & Sound",
  "Shows & Entertainment",
  "Space Design & Spatial Art",
  "Illustration, Graphic Design & Animation",
  "Digital, Immersive & Tech Art",
  "Web, UX & UI Design",
  "Multi-Sensory Experiences",
  "Live & Event Art",
  "Objects & Collectibles",
  "Photography",
  "Videography",
  "Writing & Storytelling",
  "Hair, Make-up & Styling",
  "Hosts, Moderators & Speakers",
  "Creative Direction & Consulting",
  "Creative Workshops",
] as const;

export type CreativeField = (typeof CREATIVE_FIELDS)[number];

export const CREATIVE_SERVICES_BY_FIELD: Record<CreativeField, string[]> = {
  "Music & Sound": [
    "Audio Branding & Jingles",
    "Choir Performance",
    "Custom Composition",
    "DJ Sets",
    "Live Music",
    "Podcast Production",
    "Songwriting",
    "Sound Design",
    "Sound Scenography & Installations",
    "Spoken Word Performance",
  ],
  "Shows & Entertainment": [
    "Acrobatics",
    "Aerial Performance",
    "Balloon Art",
    "Bubble Performance",
    "Burlesque Performance",
    "Choreography",
    "Clown Performance",
    "Close-up Magic",
    "Comedy Performance",
    "Contortion",
    "Costumed Characters & Walkabout Acts",
    "Cyr Wheel Performance",
    "Dance Performance",
    "Drag Performance",
    "Fire Performance",
    "Fortune Telling",
    "Hula Hoop Performance",
    "Juggling",
    "LED & Light Performance",
    "Living Statue Performance",
    "Magic & Illusion",
    "Mime Performance",
    "Parkour & Freerunning Performance",
    "Puppet & Object Theatre",
    "Sports Performance",
    "Stilt Walking",
    "Theatre Performance",
  ],
  "Space Design & Spatial Art": [
    "Anamorphic 3D Art",
    "Botanical & Floral Installations",
    "Ceiling Art",
    "Immersive Installations",
    "Inflatable Installations",
    "Landscape & Garden Art",
    "Light Installations",
    "Mural Design & Painting",
    "Paper & Origami Installations",
    "Prop Styling",
    "Public Art & Urban Interventions",
    "Set Design",
    "Site-Specific Installations",
    "Spatial Scenography",
    "Textile Installations",
    "Video Projections & Mapping",
    "Wall Sculptures & Reliefs",
    "Wayfinding & Artistic Signage",
    "Window Display Design",
  ],
  "Illustration, Graphic Design & Animation": [
    "3D Motion Design",
    "Book & Album Cover Design",
    "Botanical & Scientific Illustration",
    "Brand Identity & Logo Design",
    "Caricatures",
    "Character & Comic Design",
    "Concept Art & Storyboarding",
    "Editorial Design",
    "Graphic Design",
    "Illustration",
    "Information Design",
    "Motion Graphics & Animation",
    "Packaging Design",
    "Pattern Design",
    "Portrait Illustration",
    "Product Illustration & Design",
    "Stop Motion",
    "Typography & Lettering",
  ],
  "Digital, Immersive & Tech Art": [
    "AI Creative Production",
    "Augmented Reality (AR) Experiences",
    "CGI & 3D Visualization",
    "Creative Coding",
    "Drone Shows",
    "Game Design",
    "Holographic Experiences",
    "Interactive Installations",
    "NFT & Digital Collectibles",
    "Real-Time Visuals",
    "Screen-Based Digital Art",
    "Virtual Reality (VR) & Extended Reality (XR) Experiences",
  ],
  "Web, UX & UI Design": ["Design Systems", "Mobile App Design", "UI Design", "UX Design", "Web Design"],
  "Multi-Sensory Experiences": [
    "Culinary Experience Design",
    "Custom Fragrance Design",
    "Haptic & Tactile Installations",
    "Multi-Sensory Experience Design",
    "Scent Installations",
  ],
  "Live & Event Art": [
    "Graphic Recording & Sketchnoting",
    "Interactive Photo Experiences",
    "Live Calligraphy & Lettering",
    "Live Caricatures",
    "Live Chalk Art",
    "Live Face & Body Painting",
    "Live Illustration & Sketching",
    "Live Painting",
    "Live Portraits",
    "Live Product & Object Customization",
    "Live Sand Art",
    "Live Printmaking",
    "Temporary Tattoos",
  ],
  "Objects & Collectibles": ["Custom Object & Collectible Design", "Original Artwork", "Sculpture"],
  Photography: [
    "Architecture & Interior Photography",
    "Commercial & Advertising Photography",
    "Editorial & Documentary Photography",
    "Event Photography",
    "Fashion Photography",
    "Food Photography",
    "Photo Retouching & Post-Production",
    "Portrait Photography",
    "Product Photography",
    "Social media content photography",
    "Wedding Photography",
  ],
  Videography: [
    "Architecture & Space Videography",
    "Brand Films & Commercial Video",
    "Editorial & Documentary Filmmaking",
    "Event Videography",
    "Livestream Production",
    "Music Videos",
    "Product Video",
    "Social media content videography",
    "Video Editing & Post-Production",
    "Wedding Videography",
  ],
  "Writing & Storytelling": [
    "Copywriting",
    "Editorial Writing",
    "Ghostwriting",
    "Scriptwriting",
    "Speechwriting",
    "Storytelling & Narrative Development",
  ],
  "Hair, Make-up & Styling": [
    "Costume Design",
    "Hair Styling",
    "Make-up Artistry",
    "Prosthetics & Special Effects (SFX) Make-up",
    "Fashion & Wardrobe Styling",
  ],
  "Hosts, Moderators & Speakers": ["Event Hosting", "Moderation", "Public Speaking"],
  "Creative Direction & Consulting": ["Art Direction", "Creative Consulting", "Creative Direction", "Curation"],
  "Creative Workshops": [
    "Calligraphy & Lettering Workshops",
    "Ceramics & Pottery Workshops",
    "Circus & Movement Workshops",
    "Dance Workshops",
    "Digital Art & Illustration Workshops",
    "DJ Workshops",
    "Drawing & Painting Workshops",
    "Floral Design Workshops",
    "Fragrance Workshops",
    "Graffiti & Street Art Workshops",
    "Music Workshops",
    "Photography Workshops",
    "Printmaking Workshops",
    "Storytelling & Creative Writing Workshops",
    "Tape Art Workshops",
    "Theatre Workshops",
    "Videography Workshops",
  ],
};

// Common Gulf/regional country codes first, then the rest alphabetically —
// ported from the original form's <select> so the same shortlist stays on
// top for the audience this form actually gets used by.
export const PHONE_COUNTRY_CODES: { code: string; label: string }[] = [
  { code: "+966", label: "+966 (Saudi Arabia)" },
  { code: "+971", label: "+971 (United Arab Emirates)" },
  { code: "+965", label: "+965 (Kuwait)" },
  { code: "+973", label: "+973 (Bahrain)" },
  { code: "+974", label: "+974 (Qatar)" },
  { code: "+968", label: "+968 (Oman)" },
  { code: "+93", label: "+93 (Afghanistan)" },
  { code: "+355", label: "+355 (Albania)" },
  { code: "+213", label: "+213 (Algeria)" },
  { code: "+376", label: "+376 (Andorra)" },
  { code: "+244", label: "+244 (Angola)" },
  { code: "+54", label: "+54 (Argentina)" },
  { code: "+374", label: "+374 (Armenia)" },
  { code: "+61", label: "+61 (Australia)" },
  { code: "+43", label: "+43 (Austria)" },
  { code: "+994", label: "+994 (Azerbaijan)" },
  { code: "+880", label: "+880 (Bangladesh)" },
  { code: "+375", label: "+375 (Belarus)" },
  { code: "+32", label: "+32 (Belgium)" },
  { code: "+501", label: "+501 (Belize)" },
  { code: "+229", label: "+229 (Benin)" },
  { code: "+975", label: "+975 (Bhutan)" },
  { code: "+591", label: "+591 (Bolivia)" },
  { code: "+387", label: "+387 (Bosnia and Herzegovina)" },
  { code: "+267", label: "+267 (Botswana)" },
  { code: "+55", label: "+55 (Brazil)" },
  { code: "+673", label: "+673 (Brunei)" },
  { code: "+359", label: "+359 (Bulgaria)" },
  { code: "+226", label: "+226 (Burkina Faso)" },
  { code: "+257", label: "+257 (Burundi)" },
  { code: "+855", label: "+855 (Cambodia)" },
  { code: "+237", label: "+237 (Cameroon)" },
  { code: "+1", label: "+1 (Canada)" },
  { code: "+235", label: "+235 (Chad)" },
  { code: "+56", label: "+56 (Chile)" },
  { code: "+86", label: "+86 (China)" },
  { code: "+57", label: "+57 (Colombia)" },
  { code: "+269", label: "+269 (Comoros)" },
  { code: "+506", label: "+506 (Costa Rica)" },
  { code: "+385", label: "+385 (Croatia)" },
  { code: "+53", label: "+53 (Cuba)" },
  { code: "+357", label: "+357 (Cyprus)" },
  { code: "+420", label: "+420 (Czechia)" },
  { code: "+45", label: "+45 (Denmark)" },
  { code: "+253", label: "+253 (Djibouti)" },
  { code: "+1809", label: "+1809 (Dominican Republic)" },
  { code: "+593", label: "+593 (Ecuador)" },
  { code: "+20", label: "+20 (Egypt)" },
  { code: "+503", label: "+503 (El Salvador)" },
  { code: "+372", label: "+372 (Estonia)" },
  { code: "+251", label: "+251 (Ethiopia)" },
  { code: "+679", label: "+679 (Fiji)" },
  { code: "+358", label: "+358 (Finland)" },
  { code: "+33", label: "+33 (France)" },
  { code: "+241", label: "+241 (Gabon)" },
  { code: "+220", label: "+220 (Gambia)" },
  { code: "+995", label: "+995 (Georgia)" },
  { code: "+49", label: "+49 (Germany)" },
  { code: "+233", label: "+233 (Ghana)" },
  { code: "+30", label: "+30 (Greece)" },
  { code: "+502", label: "+502 (Guatemala)" },
  { code: "+224", label: "+224 (Guinea)" },
  { code: "+509", label: "+509 (Haiti)" },
  { code: "+504", label: "+504 (Honduras)" },
  { code: "+852", label: "+852 (Hong Kong)" },
  { code: "+36", label: "+36 (Hungary)" },
  { code: "+354", label: "+354 (Iceland)" },
  { code: "+91", label: "+91 (India)" },
  { code: "+62", label: "+62 (Indonesia)" },
  { code: "+98", label: "+98 (Iran)" },
  { code: "+964", label: "+964 (Iraq)" },
  { code: "+353", label: "+353 (Ireland)" },
  { code: "+972", label: "+972 (Israel)" },
  { code: "+39", label: "+39 (Italy)" },
  { code: "+225", label: "+225 (Ivory Coast)" },
  { code: "+1876", label: "+1876 (Jamaica)" },
  { code: "+81", label: "+81 (Japan)" },
  { code: "+962", label: "+962 (Jordan)" },
  { code: "+7", label: "+7 (Kazakhstan)" },
  { code: "+254", label: "+254 (Kenya)" },
  { code: "+383", label: "+383 (Kosovo)" },
  { code: "+996", label: "+996 (Kyrgyzstan)" },
  { code: "+856", label: "+856 (Laos)" },
  { code: "+371", label: "+371 (Latvia)" },
  { code: "+961", label: "+961 (Lebanon)" },
  { code: "+266", label: "+266 (Lesotho)" },
  { code: "+231", label: "+231 (Liberia)" },
  { code: "+218", label: "+218 (Libya)" },
  { code: "+423", label: "+423 (Liechtenstein)" },
  { code: "+370", label: "+370 (Lithuania)" },
  { code: "+352", label: "+352 (Luxembourg)" },
  { code: "+261", label: "+261 (Madagascar)" },
  { code: "+265", label: "+265 (Malawi)" },
  { code: "+60", label: "+60 (Malaysia)" },
  { code: "+960", label: "+960 (Maldives)" },
  { code: "+223", label: "+223 (Mali)" },
  { code: "+356", label: "+356 (Malta)" },
  { code: "+222", label: "+222 (Mauritania)" },
  { code: "+230", label: "+230 (Mauritius)" },
  { code: "+52", label: "+52 (Mexico)" },
  { code: "+373", label: "+373 (Moldova)" },
  { code: "+377", label: "+377 (Monaco)" },
  { code: "+976", label: "+976 (Mongolia)" },
  { code: "+382", label: "+382 (Montenegro)" },
  { code: "+212", label: "+212 (Morocco)" },
  { code: "+258", label: "+258 (Mozambique)" },
  { code: "+95", label: "+95 (Myanmar)" },
  { code: "+264", label: "+264 (Namibia)" },
  { code: "+977", label: "+977 (Nepal)" },
  { code: "+31", label: "+31 (Netherlands)" },
  { code: "+64", label: "+64 (New Zealand)" },
  { code: "+505", label: "+505 (Nicaragua)" },
  { code: "+227", label: "+227 (Niger)" },
  { code: "+234", label: "+234 (Nigeria)" },
  { code: "+850", label: "+850 (North Korea)" },
  { code: "+389", label: "+389 (North Macedonia)" },
  { code: "+47", label: "+47 (Norway)" },
  { code: "+92", label: "+92 (Pakistan)" },
  { code: "+970", label: "+970 (Palestine)" },
  { code: "+507", label: "+507 (Panama)" },
  { code: "+675", label: "+675 (Papua New Guinea)" },
  { code: "+595", label: "+595 (Paraguay)" },
  { code: "+51", label: "+51 (Peru)" },
  { code: "+63", label: "+63 (Philippines)" },
  { code: "+48", label: "+48 (Poland)" },
  { code: "+351", label: "+351 (Portugal)" },
  { code: "+40", label: "+40 (Romania)" },
  { code: "+7", label: "+7 (Russia)" },
  { code: "+250", label: "+250 (Rwanda)" },
  { code: "+221", label: "+221 (Senegal)" },
  { code: "+381", label: "+381 (Serbia)" },
  { code: "+232", label: "+232 (Sierra Leone)" },
  { code: "+65", label: "+65 (Singapore)" },
  { code: "+421", label: "+421 (Slovakia)" },
  { code: "+386", label: "+386 (Slovenia)" },
  { code: "+252", label: "+252 (Somalia)" },
  { code: "+27", label: "+27 (South Africa)" },
  { code: "+82", label: "+82 (South Korea)" },
  { code: "+211", label: "+211 (South Sudan)" },
  { code: "+34", label: "+34 (Spain)" },
  { code: "+94", label: "+94 (Sri Lanka)" },
  { code: "+249", label: "+249 (Sudan)" },
  { code: "+597", label: "+597 (Suriname)" },
  { code: "+46", label: "+46 (Sweden)" },
  { code: "+41", label: "+41 (Switzerland)" },
  { code: "+963", label: "+963 (Syria)" },
  { code: "+886", label: "+886 (Taiwan)" },
  { code: "+992", label: "+992 (Tajikistan)" },
  { code: "+255", label: "+255 (Tanzania)" },
  { code: "+66", label: "+66 (Thailand)" },
  { code: "+228", label: "+228 (Togo)" },
  { code: "+1868", label: "+1868 (Trinidad and Tobago)" },
  { code: "+216", label: "+216 (Tunisia)" },
  { code: "+90", label: "+90 (Turkey)" },
  { code: "+993", label: "+993 (Turkmenistan)" },
  { code: "+256", label: "+256 (Uganda)" },
  { code: "+380", label: "+380 (Ukraine)" },
  { code: "+44", label: "+44 (United Kingdom)" },
  { code: "+1", label: "+1 (United States)" },
  { code: "+598", label: "+598 (Uruguay)" },
  { code: "+998", label: "+998 (Uzbekistan)" },
  { code: "+58", label: "+58 (Venezuela)" },
  { code: "+84", label: "+84 (Vietnam)" },
  { code: "+967", label: "+967 (Yemen)" },
  { code: "+260", label: "+260 (Zambia)" },
  { code: "+263", label: "+263 (Zimbabwe)" },
];
