// Manually-synced mirror of frontend/src/data/creativeTaxonomy.ts's
// SERVICE_TO_FIELD map — same "no shared build step between the two
// packages" approach already used for types/index.ts (see that file's
// header comment). Only what the Worker actually needs: resolving which
// Creative Field a legacy service name belongs to, for the schema v2
// migration (migrateCreativeToServices in lib/kv.ts). Keep this in sync
// by hand if the taxonomy ever changes — it's data, not logic, so drift
// only affects which field a migrated service gets filed under, never
// correctness of the migration itself.

const CREATIVE_TAXONOMY: Record<string, string[]> = {
  "Music & Sound": [
    "Audio Branding & Jingles",
    "Choir Performance",
    "Custom Composition",
    "DJ Sets",
    "Live Music",
    "Podcast Production",
    "Songwriting",
    "Sound Design",
    "Sound Scenography & Installations",
    "Spoken Word Performance",
  ],
  "Shows & Entertainment": [
    "Acrobatics",
    "Aerial Performance",
    "Balloon Art",
    "Bubble Performance",
    "Burlesque Performance",
    "Choreography",
    "Clown Performance",
    "Close-up Magic",
    "Comedy Performance",
    "Contortion",
    "Costumed Characters & Walkabout Acts",
    "Cyr Wheel Performance",
    "Dance Performance",
    "Drag Performance",
    "Fire Performance",
    "Fortune Telling",
    "Hula Hoop Performance",
    "Juggling",
    "LED & Light Performance",
    "Living Statue Performance",
    "Magic & Illusion",
    "Mime Performance",
    "Parkour & Freerunning Performance",
    "Puppet & Object Theatre",
    "Sports Performance",
    "Stilt Walking",
    "Theatre Performance",
  ],
  "Space Design & Spatial Art": [
    "Anamorphic 3D Art",
    "Botanical & Floral Installations",
    "Ceiling Art",
    "Immersive Installations",
    "Inflatable Installations",
    "Landscape & Garden Art",
    "Light Installations",
    "Mural Design & Painting",
    "Paper & Origami Installations",
    "Prop Styling",
    "Public Art & Urban Interventions",
    "Set Design",
    "Site-Specific Installations",
    "Spatial Scenography",
    "Textile Installations",
    "Video Projections & Mapping",
    "Wall Sculptures & Reliefs",
    "Wayfinding & Artistic Signage",
    "Window Display Design",
  ],
  "Illustration, Graphic Design & Animation": [
    "3D Motion Design",
    "Book & Album Cover Design",
    "Botanical & Scientific Illustration",
    "Brand Identity & Logo Design",
    "Caricatures",
    "Character & Comic Design",
    "Concept Art & Storyboarding",
    "Editorial Design",
    "Graphic Design",
    "Illustration",
    "Information Design",
    "Motion Graphics & Animation",
    "Packaging Design",
    "Pattern Design",
    "Portrait Illustration",
    "Product Illustration & Design",
    "Stop Motion",
    "Typography & Lettering",
  ],
  "Digital, Immersive & Tech Art": [
    "AI Creative Production",
    "Augmented Reality (AR) Experiences",
    "CGI & 3D Visualization",
    "Creative Coding",
    "Drone Shows",
    "Game Design",
    "Holographic Experiences",
    "Interactive Installations",
    "NFT & Digital Collectibles",
    "Real-Time Visuals",
    "Screen-Based Digital Art",
    "Virtual Reality (VR) & Extended Reality (XR) Experiences",
  ],
  "Web, UX & UI Design": ["Design Systems", "Mobile App Design", "UI Design", "UX Design", "Web Design"],
  "Multi-Sensory Experiences": [
    "Culinary Experience Design",
    "Custom Fragrance Design",
    "Haptic & Tactile Installations",
    "Multi-Sensory Experience Design",
    "Scent Installations",
  ],
  "Live & Event Art": [
    "Graphic Recording & Sketchnoting",
    "Interactive Photo Experiences",
    "Live Calligraphy & Lettering",
    "Live Caricatures",
    "Live Chalk Art",
    "Live Face & Body Painting",
    "Live Illustration & Sketching",
    "Live Painting",
    "Live Portraits",
    "Live Product & Object Customization",
    "Live Sand Art",
    "Live Printmaking",
    "Temporary Tattoos",
  ],
  "Objects & Collectibles": ["Custom Object & Collectible Design", "Original Artwork", "Sculpture"],
  Photography: [
    "Architecture & Interior Photography",
    "Commercial & Advertising Photography",
    "Editorial & Documentary Photography",
    "Event Photography",
    "Fashion Photography",
    "Food Photography",
    "Photo Retouching & Post-Production",
    "Portrait Photography",
    "Product Photography",
    "Social media content photography",
    "Wedding Photography",
  ],
  Videography: [
    "Architecture & Space Videography",
    "Brand Films & Commercial Video",
    "Editorial & Documentary Filmmaking",
    "Event Videography",
    "Livestream Production",
    "Music Videos",
    "Product Video",
    "Social media content videography",
    "Video Editing & Post-Production",
    "Wedding Videography",
  ],
  "Writing & Storytelling": [
    "Copywriting",
    "Editorial Writing",
    "Ghostwriting",
    "Scriptwriting",
    "Speechwriting",
    "Storytelling & Narrative Development",
  ],
  "Hair, Make-up & Styling": [
    "Costume Design",
    "Hair Styling",
    "Make-up Artistry",
    "Prosthetics & Special Effects (SFX) Make-up",
    "Fashion & Wardrobe Styling",
  ],
  "Hosts, Moderators & Speakers": ["Event Hosting", "Moderation", "Public Speaking"],
  "Creative Direction & Consulting": ["Art Direction", "Creative Consulting", "Creative Direction", "Curation"],
  "Creative Workshops": [
    "Calligraphy & Lettering Workshops",
    "Ceramics & Pottery Workshops",
    "Circus & Movement Workshops",
    "Dance Workshops",
    "Digital Art & Illustration Workshops",
    "DJ Workshops",
    "Drawing & Painting Workshops",
    "Floral Design Workshops",
    "Fragrance Workshops",
    "Graffiti & Street Art Workshops",
    "Music Workshops",
    "Photography Workshops",
    "Printmaking Workshops",
    "Storytelling & Creative Writing Workshops",
    "Tape Art Workshops",
    "Theatre Workshops",
    "Videography Workshops",
  ],
};

const SERVICE_TO_FIELD: Record<string, string> = Object.fromEntries(
  Object.entries(CREATIVE_TAXONOMY).flatMap(([field, services]) => services.map((service) => [service, field])),
);

export function fieldForService(service: string): string | undefined {
  return SERVICE_TO_FIELD[service];
}
